"""v8__table_modifiyed_

Revision ID: e96f48533d77
Revises: f3becdd6fef9
Create Date: 2025-01-22 09:52:22.579642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96f48533d77'
down_revision: Union[str, None] = 'f3becdd6fef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_likes_comment_id_fkey', 'comment_likes', type_='foreignkey')
    op.drop_constraint('comment_likes_user_id_fkey', 'comment_likes', type_='foreignkey')
    op.drop_constraint('comment_likes_post_id_fkey', 'comment_likes', type_='foreignkey')
    op.create_foreign_key(None, 'comment_likes', 'posts', ['post_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'comment_likes', 'comments', ['comment_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'comment_likes', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'comments', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_constraint('followers_user_id_fkey', 'followers', type_='foreignkey')
    op.drop_constraint('followers_follower_id_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'followers', 'user', ['follower_id'], ['id'], ondelete='cascade')
    op.drop_constraint('post_like_post_id_fkey', 'post_like', type_='foreignkey')
    op.drop_constraint('post_like_user_id_fkey', 'post_like', type_='foreignkey')
    op.create_foreign_key(None, 'post_like', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'post_like', 'posts', ['post_id'], ['id'], ondelete='cascade')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'user', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.drop_constraint(None, 'post_like', type_='foreignkey')
    op.create_foreign_key('post_like_user_id_fkey', 'post_like', 'user', ['user_id'], ['id'])
    op.create_foreign_key('post_like_post_id_fkey', 'post_like', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_follower_id_fkey', 'followers', 'user', ['follower_id'], ['id'])
    op.create_foreign_key('followers_user_id_fkey', 'followers', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.drop_constraint(None, 'comment_likes', type_='foreignkey')
    op.create_foreign_key('comment_likes_post_id_fkey', 'comment_likes', 'posts', ['post_id'], ['id'])
    op.create_foreign_key('comment_likes_user_id_fkey', 'comment_likes', 'user', ['user_id'], ['id'])
    op.create_foreign_key('comment_likes_comment_id_fkey', 'comment_likes', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###
