"""v7_follows_table_change_and_user

Revision ID: f3becdd6fef9
Revises: e29b8d107ce3
Create Date: 2025-01-21 12:35:45.446520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3becdd6fef9'
down_revision: Union[str, None] = 'e29b8d107ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('followers_followed_id_fkey', 'followers', type_='foreignkey')
    op.create_foreign_key(None, 'followers', 'user', ['user_id'], ['id'])
    op.drop_column('followers', 'followed_id')
    op.add_column('user', sa.Column('follow_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'follow_count')
    op.add_column('followers', sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'followers', type_='foreignkey')
    op.create_foreign_key('followers_followed_id_fkey', 'followers', 'user', ['followed_id'], ['id'])
    op.drop_column('followers', 'user_id')
    # ### end Alembic commands ###
